<?php 
require_once('../main/auth.php');
include ('../connect.php');
$result = $db->prepare("SELECT * FROM patients");
        $result->execute();
        $rowcountt = $result->rowcount();
        $rowcount = $rowcountt+1;
        $code=$rowcount.date("/Y");
 ?>
 <!DOCTYPE html>
<html>
<title>register patient</title>
<?php 
include "../header.php";
?>
<head>
</head>

  <header class="header clearfix" style="background-color: #3786d6;;">
    

    </button>
    <?php include('../main/nav.php'); ?>
   
  </header><?php include('side.php'); ?>
  <div class="content-wrapper">      
      <div class="jumbotron" style="background: #95CAFC;">
        <link rel="stylesheet" href="../main/jquery-ui.css">
  <script src="../main/jquery-1.12.4.js"></script>
  <script src="../main/jquery-ui.js"></script>
  <div class="wrapper">  
            <h3>register walk in patient</h3>
          <style type="text/css">
            #register{
              border-style: inset;  background-image: url('../images/bg.jpg');
              margin-left: -30%;

            }
            @media only screen and (max-width: 600px) {
    #register {
         margin-left: 0%;
    }
}
          </style>
          <script>
  $( function() {
    $( "#mydate" ).datepicker({
      yearRange: "-100:+0",
      changeMonth: true,
      changeYear: true
    });
  } );

  </script>
          <div class="container" id="register" >
    <form action="save_walk_in.php" method="post">
  <div class="form-row">
    <div class="form-group col-md-4">
      <label for="name">patient name</label>
      <input type="text" class="form-control" name="name"  placeholder="patient name" required="true" />
    </div>
    <div class="form-group col-md-4">
      <label for="name">date of birth</label>
      <input type="text" id="mydate" class="form-control" name="age" placeholder="date of birth in dd-mm-yyyy" autocomplete="off" required>
    </div>
    <div class="form-group col-md-4">
     
      <label for="inputPassword4">Patient number(autogenerated)</label>
      <input type="text" class="form-control" name="number" value="<?php echo mt_rand(10000000, 99999999); ?>" readonly>
    </div>
  </div>
  <button class="btn btn-success btn-large" style="width: 80%; margin-left:10%;">save</button></form>  
</div>
</div>
 

            
          
            

</body>
</html>