<?php 
require_once('../main/auth.php');
include ('../connect.php');
$result = $db->prepare("SELECT * FROM patients");
        $result->execute();
        $rowcountt = $result->rowcount();
        $rowcount = $rowcountt+1;
        $code=$rowcount.date("/Y");
 ?>
 <!DOCTYPE html>
<html>
<title>register patient</title>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <link href='../pharmacy/googleapis.css' rel='stylesheet'>
  <link href='../pharmacy/src/vendor/normalize.css/normalize.css' rel='stylesheet'>
  <link href='../pharmacy/src/vendor/fontawesome/css/font-awesome.min.css' rel='stylesheet'>
  <link href="../pharmacy/dist/vertical-responsive-menu.min.css" rel="stylesheet">
  <link href="../pharmacy/demo.css" rel="stylesheet">
  <link rel="stylesheet" href="../css/bootstrap.min.css">
  <link rel="stylesheet" href="dist/css/bootstrap-select.css">
  <script src="../js/jquery.min.js"></script>
  <script src="../js/bootstrap.min.js"></script>
  <script src="dist/js/bootstrap-select.js"></script>
  <link href="../src/facebox.css" media="screen" rel="stylesheet" type="text/css" />
<script src="../src/facebox.js" type="text/javascript"></script>
<script type="text/javascript">
  jQuery(document).ready(function($) {
    $('a[rel*=facebox]').facebox({
      loadingImage : '../src/loading.gif',
      closeImage   : '../src/closelabel.png'
    })
  })
</script>

</head>
  <body onLoad="document.getElementById('country').focus();">
  <header class="header clearfix" style="background-color: #3786d6;;">
    <button type="button" id="toggleMenu" class="toggle_menu">
      <i class="fa fa-bars"></i>

    </button>
    <?php include('../main/nav.php'); ?>
   
  </header><?php include('side.php'); ?>
  <div class="content-wrapper">      
      <div class="jumbotron" style="background: #95CAFC;">
        <link rel="stylesheet" href="../main/jquery-ui.css">
  <script src="../main/jquery-1.12.4.js"></script>
  <script src="../main/jquery-ui.js"></script>
  <div class="wrapper">  
            <h3>register walk in patient</h3>
          <style type="text/css">
            #register{
              border-style: inset;  background-image: url('../images/bg.jpg');
              margin-left: -30%;

            }
            @media only screen and (max-width: 600px) {
    #register {
         margin-left: 0%;
    }
}
          </style>
          <div class="container" id="register" >
    <form action="save_walk_in.php" method="post">
  <div class="form-row">
    <div class="form-group col-md-6">
      <label for="name">patient name</label>
      <input type="text" class="form-control" name="name"  placeholder="patient name" required="true" />
    </div>
    <div class="form-group col-md-6">
     
      <label for="inputPassword4">Patient number(autogenerated)</label>
      <input type="text" class="form-control" name="number" value="<?php echo mt_rand(10000000, 99999999); ?>" readonly>
    </div>
  </div>
  <button class="btn btn-success btn-large" style="width: 80%; margin-left:10%;">save</button></form>  
</div>
</div>
 

            
          
            

</body>
</html>